# Generated by Django 5.2 on 2025-04-21 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('conducted_by', models.CharField(max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='activity_attachments/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('faculty', models.ManyToManyField(related_name='activity_faculty', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(related_name='activity_staff', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='activity_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
