# Generated by Django 5.2 on 2025-04-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fees_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
