# Generated by Django 5.2 on 2025-05-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_fees_expenses_activity_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
