# Generated by Django 5.2 on 2025-05-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
